# Use Python slim base
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

# Copy only requirements first (for build caching)
COPY ../requirements/base.txt ./requirements/base.txt
COPY ../requirements/voice_screening_ui.txt ./requirements/voice_screening_ui.txt
# Install Streamlit + base deps
RUN pip install --no-cache-dir -r requirements/voice_screening_ui.txt

# Copy project source code
COPY ../src ./src

ENV PYTHONPATH=/app


# Expose Streamlit port
EXPOSE 8501

# Default command to run Streamlit app
CMD ["streamlit", "run", "src/frontend/streamlit/voice_screening_ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
